site: Maesoser Blog
url: maesoser.github.io
title: Maesoser
description: Just a bunch of notes.
twitter:
  username: maesoser
  card: summary
  creator: maesoser
author:
  twitter: maesoser
  name: maesoser
  avatar:
  email: #youremail
  url: maesoser.github.io
permalink: pretty

baseurl: "maesoser.github.io"

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"